Add basic logging support
GoogleCloudPlatform/keyrotator pull request #1
Opened 2017-02-01 21:53 UTC by mirons-google

This includes a dynamic logfile. It also replaces all print messages in favor of two logging streams for console and a file.

2017-02-01 23:37 UTC, carise commented on keyrotator/create.py
> +      loggin.debug("Key details: %s",
loggin - typo?

2017-02-01 23:38 UTC, carise requested changes
Looks ok, is the test.log file necessary or can it be removed?

2017-02-02 01:09 UTC, mirons-google commented
Fixed. PTAL.

2017-02-02 01:38 UTC, carise commented on keyrotator/list_keys.py
> +        logging.info("Key: %s\n\tCreated: %s\n\tExpires: %s", key_path.group(1), key["validAfterTime"], key["validBeforeTime"])
Could you change so the line length is 80 chars?

2017-02-02 01:38 UTC, carise commented on keyrotator/list.py
> +        logging.info("Key: %s\n\tCreated: %s\n\tExpires: %s", key_path.group(1), key["validAfterTime"], key["validBeforeTime"])
Line length should be <= 80 chars

2017-02-02 01:48 UTC, carise approved these changes
LGTM

2017-02-02 01:52 UTC, merged